spring:
  application:
    name: VaultApp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hackathon
  http:
    multipart:
      max-file-size: 128000MB
      max-request-size: 128000MB
server:
  httpProtocol: http
  host: localhost
  port: 8282
  contextPath: /
  sessionTimeout: 600
multipart:
  enabled: true
  location: /tmp/filess/
vault:
  type: local
local:
  vault_dir: raw/
cloud:
  aws:
    credentials:
      accessKey: AKIAJSIKGVFQIQTAM73Q
      secretKey: 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
    region: us-east-2
    s3:
      bucket: vault.raw